language: scala
scala:
  - 2.12.4
sudo: false

script:
  - sbt server/test client/test

cache:
  directories:
    - $HOME/.ivy2/cache
    - $HOME/.sbt
    - $HOME/.cache/sbt-scalafmt
    - $HOME/.coursier/cache
before_cache:
  # Cleanup the cached directories to avoid unnecessary cache updates
  - find $HOME/.ivy2/cache -name "ivydata-*.properties" -print -delete
  - find $HOME/.sbt        -name "*.lock"               -print -delete
